// Mocks generated by Mockito 5.4.4 from annotations
// in lumina/test/webdav_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:lumina/src/core/services/epub_import_service.dart' as _i10;
import 'package:lumina/src/features/library/domain/book_manifest.dart' as _i12;
import 'package:lumina/src/features/library/domain/shelf_book.dart' as _i11;
import 'package:lumina/src/features/sync/data/sync_config_repository.dart'
    as _i8;
import 'package:lumina/src/features/sync/data/webdav_service.dart' as _i2;
import 'package:lumina/src/features/sync/domain/sync_config.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:webdav_client/webdav_client.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WebDavService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebDavService extends _i1.Mock implements _i2.WebDavService {
  MockWebDavService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<String, bool>> initialize({
    required String? serverUrl,
    required String? username,
    required String? password,
    required String? remoteFolderPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #serverUrl: serverUrl,
            #username: username,
            #password: password,
            #remoteFolderPath: remoteFolderPath,
          },
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #initialize,
            [],
            {
              #serverUrl: serverUrl,
              #username: username,
              #password: password,
              #remoteFolderPath: remoteFolderPath,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #testConnection,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> ensureRemoteDirectory() =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureRemoteDirectory,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #ensureRemoteDirectory,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> uploadFile({
    required _i6.File? localFile,
    required String? remoteFileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #localFile: localFile,
            #remoteFileName: remoteFileName,
          },
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #localFile: localFile,
              #remoteFileName: remoteFileName,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> uploadText({
    required String? content,
    required String? remoteFileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadText,
          [],
          {
            #content: content,
            #remoteFileName: remoteFileName,
          },
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #uploadText,
            [],
            {
              #content: content,
              #remoteFileName: remoteFileName,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, List<int>>> downloadFile(
          String? remoteFileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [remoteFileName],
        ),
        returnValue: _i3.Future<_i4.Either<String, List<int>>>.value(
            _i5.dummyValue<_i4.Either<String, List<int>>>(
          this,
          Invocation.method(
            #downloadFile,
            [remoteFileName],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, List<int>>>);

  @override
  _i3.Future<_i4.Either<String, String>> downloadText(String? remoteFileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadText,
          [remoteFileName],
        ),
        returnValue: _i3.Future<_i4.Either<String, String>>.value(
            _i5.dummyValue<_i4.Either<String, String>>(
          this,
          Invocation.method(
            #downloadText,
            [remoteFileName],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, String>>);

  @override
  _i3.Future<_i4.Either<String, List<_i7.File>>> listFiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #listFiles,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<String, List<_i7.File>>>.value(
            _i5.dummyValue<_i4.Either<String, List<_i7.File>>>(
          this,
          Invocation.method(
            #listFiles,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, List<_i7.File>>>);

  @override
  _i3.Future<_i4.Either<String, List<_i7.File>>> listFilesByPath(
          String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFilesByPath,
          [path],
        ),
        returnValue: _i3.Future<_i4.Either<String, List<_i7.File>>>.value(
            _i5.dummyValue<_i4.Either<String, List<_i7.File>>>(
          this,
          Invocation.method(
            #listFilesByPath,
            [path],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, List<_i7.File>>>);

  @override
  _i3.Future<bool> fileExists(String? remoteFileName) => (super.noSuchMethod(
        Invocation.method(
          #fileExists,
          [remoteFileName],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Either<String, bool>> deleteFile(String? remoteFileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [remoteFileName],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteFile,
            [remoteFileName],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, DateTime?>> getFileModifiedDate(
          String? remoteFileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileModifiedDate,
          [remoteFileName],
        ),
        returnValue: _i3.Future<_i4.Either<String, DateTime?>>.value(
            _i5.dummyValue<_i4.Either<String, DateTime?>>(
          this,
          Invocation.method(
            #getFileModifiedDate,
            [remoteFileName],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, DateTime?>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SyncConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncConfigRepository extends _i1.Mock
    implements _i8.SyncConfigRepository {
  MockSyncConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i9.SyncConfig?> getConfig() => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [],
        ),
        returnValue: _i3.Future<_i9.SyncConfig?>.value(),
      ) as _i3.Future<_i9.SyncConfig?>);

  @override
  _i3.Future<_i4.Either<String, bool>> saveConfig(_i9.SyncConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConfig,
          [config],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #saveConfig,
            [config],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> saveField(
    String? field,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveField,
          [
            field,
            value,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #saveField,
            [
              field,
              value,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> updateLastSync({
    DateTime? syncDate,
    String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastSync,
          [],
          {
            #syncDate: syncDate,
            #error: error,
          },
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #updateLastSync,
            [],
            {
              #syncDate: syncDate,
              #error: error,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<_i4.Either<String, bool>> deleteConfig() => (super.noSuchMethod(
        Invocation.method(
          #deleteConfig,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteConfig,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);

  @override
  _i3.Future<bool> isConfigured() => (super.noSuchMethod(
        Invocation.method(
          #isConfigured,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [EpubImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpubImportService extends _i1.Mock implements _i10.EpubImportService {
  MockEpubImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<String, _i11.ShelfBook>> importBook(_i6.File? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #importBook,
          [file],
        ),
        returnValue: _i3.Future<_i4.Either<String, _i11.ShelfBook>>.value(
            _i5.dummyValue<_i4.Either<String, _i11.ShelfBook>>(
          this,
          Invocation.method(
            #importBook,
            [file],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, _i11.ShelfBook>>);

  @override
  _i3.Future<_i4.Either<String, (_i12.BookManifest, String?)>>
      updateBookManifestAndCover(
    String? epubAbsPath,
    int? bookId,
    String? fileHash,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateBookManifestAndCover,
              [
                epubAbsPath,
                bookId,
                fileHash,
              ],
            ),
            returnValue: _i3
                .Future<_i4.Either<String, (_i12.BookManifest, String?)>>.value(
                _i5.dummyValue<
                    _i4.Either<String, (_i12.BookManifest, String?)>>(
              this,
              Invocation.method(
                #updateBookManifestAndCover,
                [
                  epubAbsPath,
                  bookId,
                  fileHash,
                ],
              ),
            )),
          ) as _i3.Future<_i4.Either<String, (_i12.BookManifest, String?)>>);

  @override
  _i3.Future<_i4.Either<String, bool>> deleteBook(_i11.ShelfBook? book) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [book],
        ),
        returnValue: _i3.Future<_i4.Either<String, bool>>.value(
            _i5.dummyValue<_i4.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteBook,
            [book],
          ),
        )),
      ) as _i3.Future<_i4.Either<String, bool>>);
}
