targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          exclude:
            - lib/src/rust/**
      
      isar_community_generator:
        generate_for:
          exclude:
            - lib/src/rust/**