// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build the name→index table for the EPUB at `epub_path`.
///
/// Only reads the ZIP Central Directory (located at the end of the file).
/// No file content is decompressed.  Idempotent: a second call for the same
/// path is a no-op.
Future<void> loadEpub({required String epubPath}) =>
    RustLib.instance.api.crateApiEpubLoadEpub(epubPath: epubPath);

/// Read a single file from the EPUB (lazy: decompresses only the requested
/// entry).
///
/// Concurrency:
///   * The read lock is held **only** while looking up the entry index
///     (HashMap get, O(1), < 1 µs).
///   * The actual decompression happens after the lock is released, so many
///     callers can decompress different entries at the same time.
Future<Uint8List?> readEpubFile({
  required String epubPath,
  required String filePath,
}) => RustLib.instance.api.crateApiEpubReadEpubFile(
  epubPath: epubPath,
  filePath: filePath,
);

/// Remove an EPUB's index from memory.
/// Call this when the reader is closed to free memory.
Future<void> closeEpub({required String epubPath}) =>
    RustLib.instance.api.crateApiEpubCloseEpub(epubPath: epubPath);
