// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_media_file`, `normalize_path`, `parse_central_directory`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedArchive`

/// Parse the ZIP central directory for the EPUB at `epub_path` and cache the
/// result.  No decompression occurs here.
///
/// Idempotent: a second call for the same path is a no-op and returns
/// immediately without any I/O.
Future<void> loadEpub({required String epubPath}) =>
    RustLib.instance.api.crateApiEpubLoadEpub(epubPath: epubPath);

/// Read and decompress a single file from the EPUB.
///
/// Returns:
///   `Ok(Some(bytes))` – file found and decompressed successfully.
///   `Ok(None)`        – the entry does not exist in this EPUB.
///   `Err(msg)`        – I/O error, corrupt data, or zip-bomb detected.
///
/// # Concurrency
/// The global read-lock is held **only** for `Arc::clone` (< 1 µs).
/// All I/O and decompression happen on a private file handle with no lock
/// held, so N threads can decompress different entries simultaneously.
Future<Uint8List?> readEpubFile({
  required String epubPath,
  required String filePath,
}) => RustLib.instance.api.crateApiEpubReadEpubFile(
  epubPath: epubPath,
  filePath: filePath,
);

/// Remove the cached metadata for `epub_path`.
/// Call this when the reader is closed to free memory.
Future<void> closeEpub({required String epubPath}) =>
    RustLib.instance.api.crateApiEpubCloseEpub(epubPath: epubPath);
